# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishlist', '0002_auto_20170227_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likeditems', models.ManyToManyField(related_name='likeditems', to='wishlist.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='wishlist.User')),
            ],
        ),
    ]
